#!/usr/bin/env php
<?php
require __DIR__. '/vendor/autoload.php';
//require __DIR__.'/../src/SymVirIns/InstallerCommand.class.php';

use Symfony\Component\Console\Application;

$application = new Application('Symvirins', '@package_version@');
$application->add(new SymVirIns\InstallerCommand());
$application->run();
